config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config.merge({
    controllers: {sessions: 'users/sessions'}, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
   } )
  resources :upcoming_events do
    collection do
      get  'past_events'
      get 'upcomings'
      get 'live_events'
    end
  end
  resources :pages
  resources :news
  get 'pages/filter/:scope' => 'pages#index', as: :filtered_page
  resources :imagegalleries
  root to: 'home#index'
  resources :posts, :pictures, :aboutpages, shallow: true do
    resources :pictures
    member do
      post 'like'
      delete 'unlike'
    end
    resources :comments do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :replies
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :commentable, polymorphic: true
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
  has_many :replies, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :replies
  accepts_nested_attributes_for :pictures

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagegallery.rb
class Imagegallery < ActiveRecord::Base

  mount_uploader :image, GalleryUploader
  validates :image_description, presence: true
  validates :image_title, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true

  validates :like, presence: true
  belongs_to :user
  belongs_to :post
  belongs_to :comment
end

app/models/news.rb
class News < ActiveRecord::Base

  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }


  PAGE_TYPE = [  'Childrens',
                 'Youths',
                 'Elders',
                 'Food',
                 'Prison',
                 'Hospital',
                 'Sunday',
                 'Tuesday',
                 'Thursday',
                 'Father',
                 'Son',
                 'Holy Spirit',
                 'Home Page',
                 'Contact'
               ]


scope :children, -> { where(page_type: 'Childrens')  }
scope :youth, -> { where(page_type: 'Youths') }
scope :elder, -> { where(page_type:  'Elders')  }
scope :food, -> { where(page_type: 'Food') }
scope :prison, -> { where(page_type: 'Prisonns') }
scope :hospital, -> { where(page_type: 'Hospital') }
scope :sunday, -> { where(page_type: 'Sunday') }
scope :tuesday, -> { where(page_type: 'Tuesday') }
scope :thursday, -> { where(page_type:  'Thursday')  }
scope :father, -> { where(page_type: 'Father') }
scope :son, -> { where(page_type:  'Son')  }
scope :home, -> { where(page_type:  'Home Page')  }
scope :holy_spirit, -> { where(page_type: 'Holy Spirit') }
scope :home, -> { where(page_type: 'Home Page') }
scope :contact, -> { where(page_type: 'Contact') }


end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, PictureImageUploader

  belongs_to :user
  belongs_to :post
  belongs_to :picturable, polymorphic: true
  belongs_to :comment
  belongs_to :page
  belongs_to :upcoming_events



  # Post.find_each do |post|
  #   post.pictures.each do |p|
  #     p.image.recreate_versions! if p.image?
  #   end
  # end

  # Comment.find_each do |comment|
  #   comment.pictures.each do |c|
  #     c.image.recreate_versions! if c.image?
  #   end
  # end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures, as: :picturable

  validates :title, presence: true
  validates :post_body, presence: true
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/prison_page.rb
class PrisonPage < ActiveRecord::Base
  validates :info, presence: true

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
  validates :reply_body, presence: true
end

app/models/upcoming_event.rb
class UpcomingEvent < ActiveRecord::Base
  has_many :pictures, as: :picturable

  accepts_nested_attributes_for :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

    before_validation :params_sanitizer, only: :update

  def params_sanitizer
    if self[:roles].include?("")
    self.roles.delete("")
  end
  end

  def self.roles
    ['pastor', 'assistant pastor']
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :email, presence: true
         validates :password, presence: true
         validates :password_confirmation, presence: true
         validates :first_name, presence: true
         validates :last_name, presence: true
         validates :phone, presence: true
         validates :gender, presence: true

         has_many :posts
         has_many :comments
         has_many :replies
         has_many :pictures
         accepts_nested_attributes_for :posts


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_comment_id, except: [:like, :create]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to :back
    else
      redirect_to :back
    end
  end


  def destroy
    if @comment.user_id == current_user.id || current_user.admin?
      @comment.destroy
      respond_to do |format|
        format.json { render json: @post, location: @post }
      end
    else
      redirect_to :back
    end
  end

  def index
    @comment = Comment.all
  end

  def like
    comment = Comment.find(params[:id])
    Like.create(likeable: comment, user: current_user, like: params[:like])
    redirect_to :back
  end

  def unlike
    @comment.likes.each do |user_like|
      if user_like.user_id ==  current_user.id
        user_like.destroy
        redirect_to :back
      end
    end
  end

  def find_comment_id
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, pictures_attributes: [:id, :comment_id, :image])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def current_user_signed_in
    current_user && user_signed_in? 
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/comments/_comment.html.erb
</br>
  <hr class="devidepost">
  <div class="postboy" style="font-size:15px; margin-bottom:15px;">
    <%= comment.body %>
  </div>
  <% comment.pictures.each do |comment_pic| %>
    <%= link_to(image_tag(comment_pic.image.url(:thumb)), comment_pic, class: "img-responsive") if comment_pic.image? %>
  <% end %>
</br>

<p><%= comment.user.first_name %></p>
<%= time_ago_in_words((comment.created_at)) %>

<%= simple_form_for([comment, comment.replies.new], :defaults => { :input_html => { :class => "repy_class" } }) do |f| %>
  <% if current_user_signed_in %>
    <%= f.input :reply_body, placeholder: "Reply to this comment", label: "reply", as: :text %>
  <% end %>
<% end %>
<% if current_user_signed_in %>
  <% if comment.likes.map(&:user_id).include? current_user.id %>
  <br>
    <%= link_to "Unlike", unlike_comment_path(comment, like: true), method: 'delete', class:"btn btn-primary" %>
  <% else %>
  <br>
    <%= link_to "Like", like_comment_path(comment, like: true), method: 'post', class:"btn btn-success" %>

    <br>
    <% end %>
    <% end %>
    <% if comment.likes.size > 0 %>
      <%= pluralize( comment.likes.size, "like") %>
      <div class="fa fa-thumbs-o-up" style="font-size:20px; color:blue"  aria-hidden="true"></div>
<% end %>
</br>
<%= link_to  pluralize(comment.replies.count, "reply"), comment_replies_path(comment.id, @reply ), class:"btn btn-success", style:"margin-top:8px;" %>
</br>
<% if current_user && user_signed_in? && comment.user_id == current_user.id || current_user && current_user.admin? %>
</br>
<%= link_to "Delete Comment", comment_path(comment), data: {confirm: 'Are you sure?'},  method: :delete, remote: true,  class:"btn btn-danger" %>
<% end %>
</hr>

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build]) do |f| %>
  <%= f.input :body%>
    <%= f.simple_fields_for :pictures, Picture.new do |comment_pic| %>
      <%=comment_pic.input :image %>
    <% end %>
      <button type="submit" class="btn btn-success" id="submit" name="submit"/>Submit</button>
    </div>
  </div>
<% end %>