config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config.merge({
    controllers: {sessions: 'users/sessions'}, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
   } )
  resources :upcoming_events do
    collection do
      get  'past_events'
      get 'upcomings'
      get 'live_events'
    end
  end
  resources :pages
  resources :news
  get 'pages/filter/:scope' => 'pages#index', as: :filtered_page
  resources :imagegalleries
  root to: 'home#index'
  resources :posts, :pictures, :aboutpages, shallow: true do
    resources :pictures
    member do
      post 'like'
      delete 'unlike'
    end
    resources :comments do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :replies
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :commentable, polymorphic: true
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
  has_many :replies, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :replies
  accepts_nested_attributes_for :pictures

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagegallery.rb
class Imagegallery < ActiveRecord::Base

  mount_uploader :image, GalleryUploader
  validates :image_description, presence: true
  validates :image_title, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true

  validates :like, presence: true
  belongs_to :user
  belongs_to :post
  belongs_to :comment
end

app/models/news.rb
class News < ActiveRecord::Base

  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }


  PAGE_TYPE = [  'Childrens',
                 'Youths',
                 'Elders',
                 'Food',
                 'Prison',
                 'Hospital',
                 'Sunday',
                 'Tuesday',
                 'Thursday',
                 'Father',
                 'Son',
                 'Holy Spirit',
                 'Home Page',
                 'Contact'
               ]


scope :children, -> { where(page_type: 'Childrens')  }
scope :youth, -> { where(page_type: 'Youths') }
scope :elder, -> { where(page_type:  'Elders')  }
scope :food, -> { where(page_type: 'Food') }
scope :prison, -> { where(page_type: 'Prisonns') }
scope :hospital, -> { where(page_type: 'Hospital') }
scope :sunday, -> { where(page_type: 'Sunday') }
scope :tuesday, -> { where(page_type: 'Tuesday') }
scope :thursday, -> { where(page_type:  'Thursday')  }
scope :father, -> { where(page_type: 'Father') }
scope :son, -> { where(page_type:  'Son')  }
scope :home, -> { where(page_type:  'Home Page')  }
scope :holy_spirit, -> { where(page_type: 'Holy Spirit') }
scope :home, -> { where(page_type: 'Home Page') }
scope :contact, -> { where(page_type: 'Contact') }


end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, PictureImageUploader

  belongs_to :user
  belongs_to :post
  belongs_to :picturable, polymorphic: true
  belongs_to :comment
  belongs_to :page
  belongs_to :upcoming_events



  # Post.find_each do |post|
  #   post.pictures.each do |p|
  #     p.image.recreate_versions! if p.image?
  #   end
  # end

  # Comment.find_each do |comment|
  #   comment.pictures.each do |c|
  #     c.image.recreate_versions! if c.image?
  #   end
  # end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures, as: :picturable

  validates :title, presence: true
  validates :post_body, presence: true
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/prison_page.rb
class PrisonPage < ActiveRecord::Base
  validates :info, presence: true

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
  validates :reply_body, presence: true
end

app/models/upcoming_event.rb
class UpcomingEvent < ActiveRecord::Base
  has_many :pictures, as: :picturable

  accepts_nested_attributes_for :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

    before_validation :params_sanitizer, only: :update

  def params_sanitizer
    if self[:roles].include?("")
    self.roles.delete("")
  end
  end

  def self.roles
    ['pastor', 'assistant pastor']
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :email, presence: true
         validates :password, presence: true
         validates :password_confirmation, presence: true
         validates :first_name, presence: true
         validates :last_name, presence: true
         validates :phone, presence: true
         validates :gender, presence: true

         has_many :posts
         has_many :comments
         has_many :replies
         has_many :pictures
         accepts_nested_attributes_for :posts


end

app/helpers/comments_helper.rb
module CommentsHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def current_user_signed_in
    current_user && user_signed_in? 
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      Rccg King of Glory Parish
    </title>
    <%= stylesheet_link_tag "application", :media => "all" %>
 <%= javascript_include_tag "application" %>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
     <%= csrf_meta_tags %>

  </head>

  <body>
    <%= render  "shared/header" %>
    <% if current_page?(root_path) %>
      <%= render "shared/headertwo" %>
      <%= render "shared/three_d_image" %>
    <% end %>

    <% flash.each do |key, value| %>
<div class="message">
   <div class="alert-message <%= key %> fade in">
    <center><strong><%= value %></strong></center>
  </div>
</div>
<% end %>
    <%= yield %>
  </body>

</html>

app/views/pages/index.html.erb
<div class="pages_details">
  <table>
    <tr>
      <th class="page_image"> Image</th>
      <th class="page_description">Description</th>
    </tr>
    <tr>
      <% @pages.each do |page| %>
        <% page.pictures.each do |pic, remov| %>
          <td class="page_image"><%= image_tag(pic.image.url(:medium)) %></td>
        <% end %>
        <td><%= page.body %></td>
      <% end %>
    </tr>
  </table>
</div>

app/views/pages/new.html.erb
<table>
  <tr>
    <th class="page_image"> Image</th>
    <th class="page_description">Description</th>
  </tr>
  <tr>
    <% @pages.each do |page| %>
      <% page.pictures.each do |pic, remov| %>
        <td class="page_image"><%= image_tag(pic.image.url(:medium)) %></td>
      <% end %>
      <td><%= page.body %></td>
    <% end %>
  </tr>
</table>

app/views/shared/_events.html.erb
<nav>
  <ul>
    <li><a class="social google" href="">Google+</a></li>
    <li><a class="social facebook" href="https://web.facebook.com/RCCG-The-King-of-Glory-Cape-Town-1741406809415560/" target="_blank">Facebook</a></li>
    <li><a class="social twitter" href="https://twitter.com/pastoreaadeboye?lang=en" target="_blank">Twitter</a></li>
    <li><a class="social instagram" href="https://www.instagram.com/rccgorg/" target="_blank">Instagram</a></li>
    <br>
    <h4 class="listevent" style="color:red; font-style: italic"> List of our Events</h4>
    <li><a class="social linkedin" href="upcoming_events/upcomings">Upcoming Events</a></li>
    <li><a class="social tumblr" href="upcoming_events/past_events">Past Events</a></li>
    <li><a class="social github" href="upcoming_events/live_events">Live Events</a></li>
  </ul>
</nav>

app/views/shared/_form.html.slim
= simple_form_for [@comment, @reply] do |f|
  = f.input :reply_body
  = f.submit

app/views/shared/_header.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <div class="navbar-header">
    	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
  			<span class="sr-only">Toggle navigation</span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
		  </button>
      <a class="fa fa-home btn btn-success navbar-brand" style="color:white; font-size:20px; font-weight:bold; position:relative;" href="/">Home</a>
	  </div>

  	<div class="collapse navbar-collapse js-navbar-collapse">
  		<ul class="nav navbar-nav">
  			<li class="dropdown mega-dropdown">
  				<a href="#" class="dropdown-toggle" style="color:white; font-weight:bold;" data-toggle="dropdown">Ministries <span class="caret"></span></a>
  				<ul class="dropdown-menu mega-dropdown-menu">
  					<li class="col-sm-3">
  						<ul>
  							<li class="dropdown-header">Men Collection</li>
                  <div id="menCollection" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                      <div class="item active">
                        <a href="#"><img src="http://placehold.it/254x150/ff3546/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 1"></a>
                      </div><!-- End Item -->
                      <div class="item">
                        <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 2"></a>
                      </div><!-- End Item -->
                      <div class="item">
                        <a href="#"><img src="http://placehold.it/254x150/2ecc71/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 3"></a>
                      </div><!-- End Carousel Inner -->
                    <!-- Controls -->
                      <a class="left carousel-control" href="#menCollection" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="right carousel-control" href="#menCollection" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    </div>
                  </div><!-- /.carousel -->
                  <li class="divider"></li>
    						</ul>
    					</li>
    					<li class="col-sm-3">
    						<ul>
    							<li class="dropdown-header" style="color:white">Ministries</li>
                  <li><a href="/pages/filter/children" class="" style="font-weight:bold">Children</a></li>
                  <li><a href="/pages/filter/elder" class="" style="font-weight:bold">Elders</a></li>
                  <li><a href="/pages/filter/youth" class="" style="font-weight:bold">Youths</a></li>
                  <li><a href="/pages/filter/hospital" class="" style="font-weight:bold">Prison</a></li>
                  <li><a href="/pages/filter/prison" class="" style="font-weight:bold">Hospital</a></li>
                  <li><a href="/pages/filter/food" class="" style="font-weight:bold">Warefare</a></li>
    							<li class="divider"></li>
    						</ul>
    					</li>
    					<li class="col-sm-3">
    						<ul>
    							<li class="dropdown-header">worship Days</li>
    							<li><a href="/pages/filter/sunday" class="" style="font-weight:bold">Sunday</a></li>
    							<li><a href="/pages/filter/tuesday" class="" style="font-weight:bold">Tuesday</a></li>
    							<li><a href="/pages/filter/thursday" class="" style="font-weight:bold">Thursday</a></li>
    							<li><a href="/pages/filter/friday" class="" style="font-weight:bold">Friday</a></li>
    						</ul>
    					</li>
  			    </li>
  			  </ul>
  			</li>
        <li><a href="/news" class="fa fa-bullhorn news" style="color:white;font-weight:bold;font-size:20px; ">News</a></li>
        <li><a href="#" style="color:white;font-weight:bolder">Images</a></li>
        <li>
          <div class="btn btn-primary church_name">RCCG King Of Glory Parish
        </li>
  		</ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" style="color:white;font-weight:bold" data-toggle="dropdown" role="button" aria-expanded="false">My account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% unless current_user_signed_in %>
              <li><a href="/sign_up" style="font-weight:bold">Sign Up</a></li>
              <li><a href="/login" style="font-weight:bold">Sign In</a></li>
            <% end %>
            <% if current_user && user_signed_in? %>
              <li><a href="/logout" style="font-weight:bold">Log Out</a></li>
              <li class="divider"></li>
              <li><a href="/edit" style="font-weight:bold">Edit User</a></li>
            <% end %>
          </ul>
        </li>
        <li><a href="/pages/filter/sunday" class="fa fa-phone-square btn btn-success" style="color:white;font-weight:bold; font-size:20px;">Contacts</a></li>
      </ul>
  	</div><!-- /.nav-collapse -->
  </nav>
</div>
<!-- <li class="col-sm-3">
  <ul>
    <li class="dropdown-header">Much more</li>
                  <li><a href="#">Easy to Customize</a></li>
    <li><a href="#">Calls to action</a></li>
    <li><a href="#">Custom Fonts</a></li>
    <li><a href="#">Slide down on Hover</a></li>
  </ul>
</li> -->

app/views/shared/_headertwo.html.erb
!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>
<body style="padding:0px; margin:0px; background-color:#fff;font-family:'Open Sans',sans-serif,arial,helvetica,verdana">

  <!-- #region Jssor Slider Begin -->
  <script src="js/jssor.slider-23.1.6.min.js" type="text/javascript"></script>
  <script type="text/javascript">
      jssor_1_slider_init = function() {

          var jssor_1_SlideoTransitions = [
            [{b:0,d:600,y:-290,e:{y:27}}],
            [{b:0,d:1000,y:185},{b:1000,d:500,o:-1},{b:1500,d:500,o:1},{b:2000,d:1500,r:360},{b:3500,d:1000,rX:30},{b:4500,d:500,rX:-30},{b:5000,d:1000,rY:30},{b:6000,d:500,rY:-30},{b:6500,d:500,sX:1},{b:7000,d:500,sX:-1},{b:7500,d:500,sY:1},{b:8000,d:500,sY:-1},{b:8500,d:500,kX:30},{b:9000,d:500,kX:-30},{b:9500,d:500,kY:30},{b:10000,d:500,kY:-30},{b:10500,d:500,c:{x:87.50,t:-87.50}},{b:11000,d:500,c:{x:-87.50,t:87.50}}],
            [{b:0,d:600,x:410,e:{x:27}}],
            [{b:-1,d:1,o:-1},{b:0,d:600,o:1,e:{o:5}}],
            [{b:-1,d:1,c:{x:175.0,t:-175.0}},{b:0,d:800,c:{x:-175.0,t:175.0},e:{c:{x:7,t:7}}}],
            [{b:-1,d:1,o:-1},{b:0,d:600,x:-570,o:1,e:{x:6}}],
            [{b:-1,d:1,o:-1,r:-180},{b:0,d:800,o:1,r:180,e:{r:7}}],
            [{b:0,d:1000,y:80,e:{y:24}},{b:1000,d:1100,x:570,y:170,o:-1,r:30,sX:9,sY:9,e:{x:2,y:6,r:1,sX:5,sY:5}}],
            [{b:2000,d:600,rY:30}],
            [{b:0,d:500,x:-105},{b:500,d:500,x:230},{b:1000,d:500,y:-120},{b:1500,d:500,x:-70,y:120},{b:2600,d:500,y:-80},{b:3100,d:900,y:160,e:{y:24}}],
            [{b:0,d:1000,o:-0.4,rX:2,rY:1},{b:1000,d:1000,rY:1},{b:2000,d:1000,rX:-1},{b:3000,d:1000,rY:-1},{b:4000,d:1000,o:0.4,rX:-1,rY:-1}]
          ];

          var jssor_1_options = {
            $AutoPlay: 1,
            $Idle: 2000,
            $CaptionSliderOptions: {
              $Class: $JssorCaptionSlideo$,
              $Transitions: jssor_1_SlideoTransitions,
              $Breaks: [
                [{d:2000,b:1000}]
              ]
            },
            $ArrowNavigatorOptions: {
              $Class: $JssorArrowNavigator$
            },
            $BulletNavigatorOptions: {
              $Class: $JssorBulletNavigator$,
              $SpacingX: 12,
              $SpacingY: 6
            }
          };

          var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

          /*responsive code begin*/
          /*remove responsive code if you don't want the slider scales while window resizing*/
          function ScaleSlider() {
              var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
              if (refSize) {
                  refSize = Math.min(refSize, 600);
                  jssor_1_slider.$ScaleWidth(refSize);
              }
              else {
                  window.setTimeout(ScaleSlider, 30);
              }
          }
          ScaleSlider();
          $Jssor$.$AddEvent(window, "load", ScaleSlider);
          $Jssor$.$AddEvent(window, "resize", ScaleSlider);
          $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
          /*responsive code end*/
      };
  </script>
  <style>
      /* jssor slider bullet navigator skin 01 css */
      /*
      .jssorb01 div           (normal)
      .jssorb01 div:hover     (normal mouseover)
      .jssorb01 .av           (active)
      .jssorb01 .av:hover     (active mouseover)
      .jssorb01 .dn           (mousedown)
      */
      .jssorb01 {
          position: absolute;
      }
      .jssorb01 div, .jssorb01 div:hover, .jssorb01 .av {
          position: absolute;
          /* size of bullet elment */
          width: 12px;
          height: 12px;
          filter: alpha(opacity=70);
          opacity: .7;
          overflow: hidden;
          cursor: pointer;
          border: #000 1px solid;
      }
      .jssorb01 div { background-color: gray; }
      .jssorb01 div:hover, .jssorb01 .av:hover { background-color: #d3d3d3; }
      .jssorb01 .av { background-color: #fff; }
      .jssorb01 .dn, .jssorb01 .dn:hover { background-color: #555555; }

      /* jssor slider arrow navigator skin 02 css */
      /*
      .jssora02l                  (normal)
      .jssora02r                  (normal)
      .jssora02l:hover            (normal mouseover)
      .jssora02r:hover            (normal mouseover)
      .jssora02l.jssora02ldn      (mousedown)
      .jssora02r.jssora02rdn      (mousedown)
      */
      .jssora02l, .jssora02r {
          display: block;
          position: absolute;
          /* size of arrow element */
          width: 55px;
          height: 55px;
          cursor: pointer;
          background: url('img/a02.png') no-repeat;
          overflow: hidden;
      }
      .jssora02l { background-position: -3px -33px; }
      .jssora02r { background-position: -63px -33px; }
      .jssora02l:hover { background-position: -123px -33px; }
      .jssora02r:hover { background-position: -183px -33px; }
      .jssora02l.jssora02ldn { background-position: -3px -33px; }
      .jssora02r.jssora02rdn { background-position: -63px -33px; }
  </style>
  <div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:600px;height:300px;overflow:hidden;visibility:hidden;">
      <!-- Loading Screen -->
      <div data-u="loading" style="position:absolute;top:0px;left:0px;background-color:rgba(0,0,0,0.7);">
          <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
          <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
      </div>
      <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:600px;height:300px;overflow:hidden;">
          <div data-p="112.50">
              <img data-u="image" src="images/002.jpg" />
              <div data-u="caption" data-t="0" style="position:absolute;top:320px;left:30px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">mobile ready, touch swipe</div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/007.jpg" />
              <div data-u="caption" data-t="1" data-3d="1" style="position:absolute;top:-50px;left:125px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">time lined layer animation</div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/003.jpg" />
              <div data-u="caption" data-t="2" style="position:absolute;top:30px;left:-380px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">finger catchable right to left</div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/004.jpg" />
              <div data-u="caption" data-t="3" style="position:absolute;top:30px;left:30px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">responsive, scale smoothly</div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/005.jpg" />
              <div data-u="caption" data-t="4" style="position:absolute;top:30px;left:30px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.6);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">image, text, and custom layers</div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/006.jpg" />
              <div data-u="caption" data-t="5" style="position:absolute;top:30px;left:600px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">tons of transition type</div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/009.jpg" />
              <div data-u="caption" data-t="6" style="position:absolute;top:30px;left:30px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">visual slider maker</div>
          </div>
          <div data-b="0" data-p="112.50">
              <img data-u="image" src="images/008.jpg" />
              <div data-u="caption" data-t="7" style="position:absolute;top:-50px;left:30px;width:350px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">play in and play out</div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/011.jpg" />
              <div data-u="caption" data-t="8" data-3d="1" style="position:absolute;top:25px;left:150px;width:250px;height:250px;z-index:0;background-color:rgba(40,177,255,0.6); overflow:hidden;">
                  <div data-u="caption" data-t="9" style="position:absolute;top:100px;left:25px;width:200px;height:50px;z-index:0;font-size:24px;line-height:50px;">A Child Layer</div>
              </div>
          </div>
          <div data-p="112.50">
              <img data-u="image" src="images/010.jpg" />
              <div data-u="caption" data-t="10" data-3d="1" style="position:absolute;top:25px;left:100px;width:250px;height:250px;z-index:0;background-color:rgba(40,177,255,0.6);">
                  <div style="margin: 15px; font-size: 20px;">
                      <p>This is full customized content layer.<br />
                      </p>
                      <p>
                          Everything is allowed

                      </p>
                      You can put

                      <a href="http://wwww.jssor.com">
                          a link
                      </a> or an image

                      <img src="img/icon_chrome.png" /> here.

                  </div>
              </div>
          </div>
          <a data-u="any" href="https://www.jssor.com/wordpress.html" style="display:none">wordpress slideshow</a>
      </div>
      <!-- Bullet Navigator -->
      <div data-u="navigator" class="jssorb01" style="bottom:8px;right:8px;">
          <div data-u="prototype" style="width:12px;height:12px;"></div>
      </div>
      <!-- Arrow Navigator -->
      <span data-u="arrowleft" class="jssora02l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
      <span data-u="arrowright" class="jssora02r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
  </div>
  <script type="text/javascript">jssor_1_slider_init();</script>
  <!-- #endregion Jssor Slider End -->
</body>
</html>

app/views/shared/_index.html.slim
#page_wrapper
  #content
    - @replies.each do  |reply|
      table
        td
          div
            .reply_text
              p
                = reply.reply_body
                p
                  = "Replied by #{reply.user.first_name}"
                p
                  = "#{time_ago_in_words(reply.created_at)}"
                .delete_reply
                  p
                    -if reply[:user_id] == current_user.id || current_user && current_user.admin?
                      = link_to 'Delete', reply_path(reply), data: {confirm: 'Are you sure?'}, method: :delete
                  p
      = link_to " Back", request.referer.present? ? request.referer : default_path

app/views/shared/_three_d_image.html.erb
<!-- <div class="container">
	<div id="carousel">
    <figure><img src="images/rccg_logo.jpg" alt="" style="width:180px;height:118px; position:relative; bottom:6px; left:5px" ></figure>
    <figure><img src="images/king_of_glory.jpg" alt="" style="width:180px;height:118px; position:relative; bottom:6px; left:5px" ></figure>
    <figure><img src="images/pastor1.jpg" alt="" style="width:180px;height:118px; position:relative; bottom:18px; left:-40px;  zoom: 200%;" ></figure>
    <figure><img src="images/adeboye.jpeg" alt="" style="width:180px;height:118px; position:relative; bottom:6px; left:5px" ></figure>
    <figure><img src="images/bike.jpg" alt=""></figure>
    <figure><img src="images/bike.jpg" alt=""></figure>
    <figure><img src="images/bike.jpg" alt=""></figure>
    <figure><img src="images/bike.jpg" alt=""></figure>
    <figure><img src="images/bike.jpg" alt=""></figure>
	</div>
</div> -->