config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config.merge({
    controllers: {sessions: 'users/sessions'}, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
   } )
  resources :upcoming_events do
    collection do
      get  'past_events'
      get 'upcomings'
      get 'live_events'
    end
  end
  resources :pages
  resources :news
  get 'pages/filter/:scope' => 'pages#index', as: :filtered_page
  resources :imagegalleries
  root to: 'home#index'
  resources :posts, :pictures, :aboutpages, shallow: true do
    resources :pictures
    member do
      post 'like'
      delete 'unlike'
    end
    resources :comments do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :replies
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :commentable, polymorphic: true
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
  has_many :replies, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :replies
  accepts_nested_attributes_for :pictures

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagegallery.rb
class Imagegallery < ActiveRecord::Base

  mount_uploader :image, GalleryUploader
  validates :image_description, presence: true
  validates :image_title, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true

  validates :like, presence: true
  belongs_to :user
  belongs_to :post
  belongs_to :comment
end

app/models/news.rb
class News < ActiveRecord::Base

  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }


  PAGE_TYPE = [  'Childrens',
                 'Youths',
                 'Elders',
                 'Food',
                 'Prison',
                 'Hospital',
                 'Sunday',
                 'Tuesday',
                 'Thursday',
                 'Father',
                 'Son',
                 'Holy Spirit',
                 'Home Page',
                 'Contact'
               ]


scope :children, -> { where(page_type: 'Childrens')  }
scope :youth, -> { where(page_type: 'Youths') }
scope :elder, -> { where(page_type:  'Elders')  }
scope :food, -> { where(page_type: 'Food') }
scope :prison, -> { where(page_type: 'Prisonns') }
scope :hospital, -> { where(page_type: 'Hospital') }
scope :sunday, -> { where(page_type: 'Sunday') }
scope :tuesday, -> { where(page_type: 'Tuesday') }
scope :thursday, -> { where(page_type:  'Thursday')  }
scope :father, -> { where(page_type: 'Father') }
scope :son, -> { where(page_type:  'Son')  }
scope :home, -> { where(page_type:  'Home Page')  }
scope :holy_spirit, -> { where(page_type: 'Holy Spirit') }
scope :home, -> { where(page_type: 'Home Page') }
scope :contact, -> { where(page_type: 'Contact') }


end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, PictureImageUploader

  belongs_to :user
  belongs_to :post
  belongs_to :picturable, polymorphic: true
  belongs_to :comment
  belongs_to :page
  belongs_to :upcoming_events



  # Post.find_each do |post|
  #   post.pictures.each do |p|
  #     p.image.recreate_versions! if p.image?
  #   end
  # end

  # Comment.find_each do |comment|
  #   comment.pictures.each do |c|
  #     c.image.recreate_versions! if c.image?
  #   end
  # end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures, as: :picturable

  validates :title, presence: true
  validates :post_body, presence: true
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/prison_page.rb
class PrisonPage < ActiveRecord::Base
  validates :info, presence: true

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
  validates :reply_body, presence: true
end

app/models/upcoming_event.rb
class UpcomingEvent < ActiveRecord::Base
  has_many :pictures, as: :picturable

  accepts_nested_attributes_for :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

    before_validation :params_sanitizer, only: :update

  def params_sanitizer
    if self[:roles].include?("")
    self.roles.delete("")
  end
  end

  def self.roles
    ['pastor', 'assistant pastor']
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :email, presence: true
         validates :password, presence: true
         validates :password_confirmation, presence: true
         validates :first_name, presence: true
         validates :last_name, presence: true
         validates :phone, presence: true
         validates :gender, presence: true

         has_many :posts
         has_many :comments
         has_many :replies
         has_many :pictures
         accepts_nested_attributes_for :posts


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post_id, except: [:index, :like, :new, :create]

  def index
    @posts = Post.paginate(page: params[:page], per_page:  8)
  end

  def show
  end

  def like
    @post = Post.find(params[:id])
     Like.create(likeable: @post, user: current_user, like: params[:like])
     redirect_to :back
  end


  def unlike
    @post = @post.likes.each do |user_like|
      if user_like.user_id ==  current_user.id
        user_like.destroy
        redirect_to :back
      end
    end
  end

  def new
    if pastor
      @post = Post.new
    else
      redirect_to :back
    end
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    if pastor
      @post.save
        redirect_to posts_path
      else
        render :new
      end
  end


  def edit
  end

  def update
    if pastor
      if @post.update(post_params)
        redirect_to post_path(@post)
      else
        render new
      end
    end
  end

  def find_post_id
    @post  = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:id, :title, :post_body, pictures_attributes: [:id, :post_id, :image])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def current_user_signed_in
    current_user && user_signed_in? 
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/posts/_form.html.slim
= simple_form_for(@post, html: { multipart: true }) do |f|
  - if @post.errors.any?
    =pluralize(@post.errors.count, "error")
  - @post.errors.full_messages.each do |msg|
    ul
      li
        = msg
  = f.input :title
  = f.input :post_body
  =f.simple_fields_for :pictures, Picture.new do |ff|
    = ff.input :image, multiple: true, name: "pictures[image][]"
  = f.submit

app/views/posts/_likes.html.erb
<% if current_user_signed_in %>
  <% if @post.likes.map(&:user_id).include? current_user.id %>
    <%= link_to "Unlike", unlike_post_path(@post, like: true), method: :delete, remote: true %>
  <%else %>
    <%= link_to "Like", like_post_path(@post, like: true), remote: true, method: :post, class: "liker" %>
  <% end %>
<% end %>

app/views/posts/edit.html.slim
= render "posts/form"

app/views/posts/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <% @posts.each do |post| %>
    <div class="row item" >
      <div class="col-md-8"  style="background-color:white; margin-bottom:20px;">
        <h2><%= link_to post.title, post %></strike></h2>
        <h5><%= truncate(post.post_body, length: 280) %></h5>
        <p>posted <%= time_ago_in_words(post.created_at) %> ago</p>
        <% post.pictures.each do |pic, remov| %>
          <p><%= image_tag(pic.image.url(:medium), class: "img-responsive") if pic.image? %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.slim
h1 New Post

= render "posts/form"

app/views/posts/show.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row item" >
    <div class="col-md-8"  style="background-color:white; margin-bottom:20px;">
      <h2><%= @post.title %></strike></h2>
      <h5><%= @post.post_body %></h5>
      <p>posted <%= time_ago_in_words(@post.created_at) %> ago</p>
      <% @post.pictures.each do |pic, remov| %>
        <p><%= image_tag(pic.image.url(:medium), class: "img-responsive") if pic.image? %></p>
      <% end %>
      <% if current_user_signed_in %>
        <% if @post.likes.map(&:user_id).include? current_user.id %>
          <%= link_to "Unlike", unlike_post_path(@post, like: true), method: :delete, :class => 'unliker', style:"color: red" %>
        <%else %>
          <%= link_to "Like", like_post_path(@post, like: true), method: :post, :class => 'liker', style:"color: red; margin-top: 30px;" %>
          <%= pluralize( @post.likes.size, "like") %>
        <% end %>
      <% end %>
      <% if @post.likes.size >= 1 %>
        <div class="fa fa-thumbs-o-up" aria-hidden="true"></div>
      <% end %>
      <%= "#{@post.comments.count} Comments" %>
      <%= render @post.comments %>
      <h3> Add a Comment: </h3>
      <% if current_user_signed_in %>
        <%= render "comments/form" %>
      <% end %>
      <%= link_to "Back", request.referer.present? ? request.referer : default_path, style:"color: red" %>
    </div>
  </div>
</div>