config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config.merge({
    controllers: {sessions: 'users/sessions'}, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
   } )
  resources :upcoming_events do
    collection do
      get  'past_events'
      get 'upcomings'
      get 'live_events'
    end
  end
  resources :pages
  resources :news
  get 'pages/filter/:scope' => 'pages#index', as: :filtered_page
  resources :imagegalleries
  root to: 'home#index'
  resources :posts, :pictures, :aboutpages, shallow: true do
    resources :pictures
    member do
      post 'like'
      delete 'unlike'
    end
    resources :comments do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :replies
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :commentable, polymorphic: true
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
  has_many :replies, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :replies
  accepts_nested_attributes_for :pictures

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagegallery.rb
class Imagegallery < ActiveRecord::Base

  mount_uploader :image, GalleryUploader
  validates :image_description, presence: true
  validates :image_title, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true

  validates :like, presence: true
  belongs_to :user
  belongs_to :post
  belongs_to :comment
end

app/models/news.rb
class News < ActiveRecord::Base

  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :pictures, as: :picturable
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }


  PAGE_TYPE = [  'Childrens',
                 'Youths',
                 'Elders',
                 'Food',
                 'Prison',
                 'Hospital',
                 'Sunday',
                 'Tuesday',
                 'Thursday',
                 'Father',
                 'Son',
                 'Holy Spirit',
                 'Home Page',
                 'Contact'
               ]


scope :children, -> { where(page_type: 'Childrens')  }
scope :youth, -> { where(page_type: 'Youths') }
scope :elder, -> { where(page_type:  'Elders')  }
scope :food, -> { where(page_type: 'Food') }
scope :prison, -> { where(page_type: 'Prisonns') }
scope :hospital, -> { where(page_type: 'Hospital') }
scope :sunday, -> { where(page_type: 'Sunday') }
scope :tuesday, -> { where(page_type: 'Tuesday') }
scope :thursday, -> { where(page_type:  'Thursday')  }
scope :father, -> { where(page_type: 'Father') }
scope :son, -> { where(page_type:  'Son')  }
scope :home, -> { where(page_type:  'Home Page')  }
scope :holy_spirit, -> { where(page_type: 'Holy Spirit') }
scope :home, -> { where(page_type: 'Home Page') }
scope :contact, -> { where(page_type: 'Contact') }


end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, PictureImageUploader

  belongs_to :user
  belongs_to :post
  belongs_to :picturable, polymorphic: true
  belongs_to :comment
  belongs_to :page
  belongs_to :upcoming_events



  # Post.find_each do |post|
  #   post.pictures.each do |p|
  #     p.image.recreate_versions! if p.image?
  #   end
  # end

  # Comment.find_each do |comment|
  #   comment.pictures.each do |c|
  #     c.image.recreate_versions! if c.image?
  #   end
  # end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures, as: :picturable

  validates :title, presence: true
  validates :post_body, presence: true
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? }
end

app/models/prison_page.rb
class PrisonPage < ActiveRecord::Base
  validates :info, presence: true

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
  validates :reply_body, presence: true
end

app/models/upcoming_event.rb
class UpcomingEvent < ActiveRecord::Base
  has_many :pictures, as: :picturable

  accepts_nested_attributes_for :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

    before_validation :params_sanitizer, only: :update

  def params_sanitizer
    if self[:roles].include?("")
    self.roles.delete("")
  end
  end

  def self.roles
    ['pastor', 'assistant pastor']
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :email, presence: true
         validates :password, presence: true
         validates :password_confirmation, presence: true
         validates :first_name, presence: true
         validates :last_name, presence: true
         validates :phone, presence: true
         validates :gender, presence: true

         has_many :posts
         has_many :comments
         has_many :replies
         has_many :pictures
         accepts_nested_attributes_for :posts


end

app/controllers/upcoming_events_controller.rb
class  UpcomingEventsController < ApplicationController

  def new
    @upcoming_events =  UpcomingEvent.new
  end

  def create
    @upcoming_event = UpcomingEvent.create(upcoming_events_params)
    if @upcoming_event.save
      redirect_to upcoming_events_path
    end
  end

  def index
    @upcoming_events = UpcomingEvent.all
  end

  def upcomings
    @upcomings = UpcomingEvent.where("starting_from > ? ", Time.now)
  end

  def past_events
    @past_events = UpcomingEvent.where("ending_time < ? ", Time.now)
  end

  def live_events
     UpcomingEvent.all.find_each do |u|
       start = u.starting_from.to_datetime
     finish = u.ending_time.to_datetime
     while(start < finish) do
       start += 1.minute
       if Time.now.to_s >= u.starting_from.to_s &&  start <= u.ending_time
         @live_events = start
         return @live_events
       end
     end
    end
  end




  def upcoming_events_params
    params.require(:upcoming_event).permit(:title, :body, :starting_from, :ending_time, pictures_attributes: [:id, :upcoming_event_id, :image] )
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

  def current_user_signed_in
    current_user && user_signed_in?
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def current_user_signed_in
    current_user && user_signed_in? 
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/upcoming_events_helper.rb
module UpcomingEventsHelper


  def upcoming
    u =  UpcomingEvent.where("starting_from > ?", Time.current)
    u.all.each do |no|
      return no
    end
  end
end

app/views/upcoming_events/index.html.erb
<div class="page_wrapper_index" >
  <didv class="content" >
    <% @upcoming_events.each do |upcoming_event| %>
      <table style="width: 100%;">
        <tr>
          <td>
            <% if upcoming_event.starting_from > Time.current%>
              <div class="post_title" >
                <%= link_to upcoming_event.title, upcoming_event_path(upcoming_event)%>
              </div>
              <div class="post_body" %>
                <%= truncate(upcoming_event.body, length: 120) %>
              </div>
              <div class="post_created" >
                <%= upcoming_event.starting_from.strftime("Starting on %m/%d/%Y/%H/%M") %>
              </div>
              <div class="post_created" >
                <%= upcoming_event.ending_time.strftime("Ends on %m/%d/%Y") + " At " + upcoming_event.ending_time.strftime("%H/%M") %>
              </div>
              <div class="img img1.imgAlbum" >
                <% upcoming_event.pictures.each do |pic, remov| %>
                  <%= image_tag(pic.image.url(:medium), class: "img-responsive") if pic.image? %>
                <% end %>
              </div>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>
            <% if upcoming_event.ending_time < Time.current%>
              <h2> This Programme is live now </h2>
              <div class="post_title" >
                <%= link_to upcoming_event.title, upcoming_event_path(upcoming_event)%>
              </div>
              <div class="post_body" %>
                <%= truncate(upcoming_event.body, length: 120) %>
              </div>
              <div class="post_created" >
                <%= upcoming_event.starting_from.strftime("Starting on %m/%d/%Y/%H/%M") %>
              </div>
              <div class="post_created" >
                <%= upcoming_event.ending_time.strftime("Ends on %m/%d/%Y") + " At " + upcoming_event.ending_time.strftime("%H/%M") %>
              </div>
              <div class="img img1.imgAlbum" >
                <% upcoming_event.pictures.each do |pic, remov| %>
                  <%= image_tag(pic.image.url(:medium), class: "img-responsive") if pic.image? %>
                <% end %>
              </div>
            <% end %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/upcoming_events/live_events.html.erb
<div class="page_wrapper_index" >
  <didv class="content" >
        <div class="post_body" >
          <%= truncate(@live_events.body, length: 120) %>
        </div>
        <div class="post_created" >
          <%= @live_events.starting_from.strftime("Starting on %m/%d/%Y/%H/%M") %>
        </div>
        <div class="post_created" >
          <%= @live_events.ending_time.strftime("Ends on %m/%d/%Y/%H/%M") %>
        </div>
  </div>
</div>

app/views/upcoming_events/new.html.erb
<h3> Upcomidng Events <h3>
<%= simple_form_for  @upcoming_events do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :starting_from %>
  <%= f.input :ending_time %>
  <%= f.simple_fields_for :pictures, Picture.new  do |ff| %>
    <%= ff.input :image %>
  <%= f.submit %>
  <% end %>
<% end %>

app/views/upcoming_events/past_events.html.erb
<div class="page_wrapper_index" >
  <didv class="content" >
    <% @past_events.each do |upcoming_event| %>
        <div class="post_body" %>
          <%= truncate(upcoming_event.body, length: 120) %>
        </div>
        <div class="post_created" >
          <%= upcoming_event.starting_from.strftime("Starting on %m/%d/%Y/%H/%M") %>
        </div>
        <div class="post_created" >
          <%= upcoming_event.ending_time.strftime("Ends on %m/%d/%Y") + " At " + upcoming_event.ending_time.strftime("%H/%M") %>
        </div>
    <% end %>
  </div>
</div>

app/views/upcoming_events/upcoming.html.erb
<div class="page_wrapper_index" >
  <didv class="content" >
    <% @upcomings.each do |upcoming_event| %>
        <div class="post_body" %>
          <%= truncate(upcoming_event.body, length: 120) %>
        </div>
        <div class="post_created" >
          <%= upcoming_event.starting_from.strftime("Starting on %m/%d/%Y/%H/%M") %>
        </div>
        <div class="post_created" >
          <%= upcoming_event.ending_time.strftime("Ends on %m/%d/%Y") + " At " + upcoming_event.ending_time.strftime("%H/%M") %>
        </div>
    <% end %>
  </div>
</div>

app/views/upcoming_events/upcomings.html.erb
<div class="page_wrapper_index" >
  <didv class="content" >
    <% @upcomings.each do |upcoming_event| %>
        <div class="post_body">
          <%= truncate(upcoming_event.body, length: 120) %>
        </div>
        <div class="post_created" >
          <%= upcoming_event.starting_from.strftime("Starting on %m/%d/%Y/%H/%M") %>
        </div>
        <div class="post_created" >
          <%= upcoming_event.ending_time.strftime("Ends on %m/%d/%Y/%H/%M") %>
        </div>
    <% end %>
  </div>
</div>